name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "*"
  
jobs:

  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: compile
      run: npm run compile
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GLOBAL_AGENT.HTTP_PROXY: http://127.0.0.1:8080
      run: npm run publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: compile
      run: npm run compile
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GLOBAL_AGENT.HTTP_PROXY: http://127.0.0.1:8080
      run: npm run publish

  publish_on_win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: compile
      run: npm run compile
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GLOBAL_AGENT.HTTP_PROXY: http://127.0.0.1:8080
      run: npm run publish